name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    uses: ./.github/workflows/setup.yml

    steps:
      - name: Lint
        run: pnpm turbo lint --filter=web

  build:
    needs: typecheck
    uses: ./.github/workflows/setup.yml

    steps:
      - name: Build
        run: pnpm turbo build --filter=web